import { asset } from "@/lib/asset";

/**
 * The picture manifest.
 *
 * Generated by `scripts/build-images.mjs` from the originals in `MerethPics/`.
 * Do not edit by hand: change the captions in that script and re-run it, so a
 * picture and its description can never drift apart.
 *
 * Sources go through `asset()` because next/image does not apply `basePath`
 * to an unoptimised src, and the static export for a GitHub project page is
 * served from a sub-path.
 *
 * Width and height are the real dimensions of the emitted file, which is what
 * lets next/image reserve the space and avoid layout shift. `blurDataURL` is a
 * 20px thumbnail inlined as base64, so a heavy screenshot blurs up rather than
 * popping in.
 */

export interface Plate {
  slug: string;
  title: string;
  caption: string;
  src: string;
  /** Narrower copies that exist on disk, for the srcset. */
  widths: number[];
  width: number;
  height: number;
  blurDataURL: string;
}

export const plates: Record<string, Plate> = {
  "aurora": {
    slug: "aurora",
    title: "Under the aurora",
    caption: "The Sea of Ghosts throws light over the north for most of the year.",
    src: asset("/img/aurora.webp"),
    widths: [640, 1024],
    width: 1280,
    height: 720,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JQBOkFTgtpwxHJ6bwAP13PS3LoL9XfXgCyEVlaspn39zO+UFfE04CQIn6OeAefk+KRISqR4j/SatZZs+aIRegKJy2GcGOuj6RFooH8b4OTgAAAAA=",
  },
  "old-ways": {
    slug: "old-ways",
    title: "The old ways",
    caption: "Clevercraft is the ancestral tradition of Skyrim's people. Where you find magic and Nords together, expect a fire and a shaman.",
    src: asset("/img/old-ways.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwAAW+wPMGJEEAAA/vQig17sdtxM00MLM09qJV9IoOd+wzwWWAAA",
  },
  "mead-hall": {
    slug: "mead-hall",
    title: "A hall in the evening",
    caption: "Most of what happens on Mereth happens at a table, over a longfire.",
    src: asset("/img/mead-hall.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCdACHfLUEYKGo4j+cntKwAAP7lbIGx6N6e+6tKEj3h1WKRt6UtKHmrsa+bZM4rOV5l9+mJYL2XqVzLcu1gAAA=",
  },
  "jarls-hall": {
    slug: "jarls-hall",
    title: "The jarl's hall",
    caption: "Court is held where the hold eats. Rank here is granted, and it can be taken back.",
    src: asset("/img/jarls-hall.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JQBOgBDfa/g+FQ8Je5gAA/r2mv4ZstVGBhZwQ1+fx8I9aawJ6kwsRUAZPPU0+vpSG5ssJOtn4iGE58BLO/q7WzVe1BLVy/MAAAA==",
  },
  "hold-guard": {
    slug: "hold-guard",
    title: "The hold guard",
    caption: "Guards are players. So is whoever they are waiting for.",
    src: asset("/img/hold-guard.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JQBadBH8zI0IvHiGmYAD+wA2I7bfsaqXNBYbR+Q4y46+wrJfD48I75WON1gs0LcgIt1oRfSYDhGgEbcdIpw5fjbH9JQmlnjK742TL1GFYwFEObvHvF4TnnWMsAA==",
  },
  "longfire": {
    slug: "longfire",
    title: "Around the fire",
    caption: "Sat down, armed, and in no hurry. An ordinary evening.",
    src: asset("/img/longfire.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 753,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUAAgAPu1iqU2ppaQiMAgBMB2JYgCdMoADa3/pfrCiA77mBugAAP68ZIYIsP61PhJpBvCTRjBITjXmNB/gAsOQqHWgdgHX5feD76VfwHxmv3NNCeioChz4AAA=",
  },
  "winter-port": {
    slug: "winter-port",
    title: "A port in winter",
    caption: "Nine holds, each with its own law, its own court and its own trade.",
    src: asset("/img/winter-port.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7ABgNRYCaEd+ZwAD+hvuDv/wKCZQphVKbo8JLYGtRe6QpOAcy5ESpypXQda/DbpYgsRTMEGa+Kvj8eWSXjRJpLdXtwAA=",
  },
  "palisade": {
    slug: "palisade",
    title: "Beyond the palisade",
    caption: "The province is the whole map, and the weather in it is not on your side.",
    src: asset("/img/palisade.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZwCw7BYEQPaS9OGAoAD+1Lc9ip9y9iRrhSjUz9S3aUmcApVjnAoay3ezPuqa5utCZaIZzpCAp7JzHroUIuT3NSxfZzLGzuGbYjaz1q8wGQed8HPCAA==",
  },
  "arriving": {
    slug: "arriving",
    title: "Arriving",
    caption: "Carry weight is a real constraint. The answer to it is crafted, not bought.",
    src: asset("/img/arriving.webp"),
    widths: [640],
    width: 981,
    height: 555,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JZQC/OCGInJvlMt8nZAAA/qFsP6bf5RtVnzSqY1I40vqcFNyjOFPXBhbHJxmT/coMVjTNsjyes+1TO4+z+D+oAAA=",
  },
  "mammoths": {
    slug: "mammoths",
    title: "Giants on the road",
    caption: "Hunting, herbalism, mining, fishing. Eight gathering trades, each with its own nodes.",
    src: asset("/img/mammoths.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JZwBUgo/4DbvT2B8+J0XnVAAA/rro4dDFscShH0EzGcBft6ihyIsz8h7uZfVrM3U33c9Qru/tZth6ZE1JZbbwfbDiAAAA",
  },
  "skill-menu": {
    slug: "skill-menu",
    title: "The skill plan",
    caption: "Press K. Eighteen memory points across 51 skills, and the tier you buy is the ceiling that skill can ever reach.",
    src: asset("/img/skill-menu.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 956,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAwCdASoUAAsAPu1iqk2ppaQiMAgBMB2JZwDLLCKUYf63H+nYfSAAAP7sZrBShPAaOVahu9uDvtX3LggoZAke56NLo6tHfnAAAA==",
  },
  "spellcasting": {
    slug: "spellcasting",
    title: "A spell, finally",
    caption: "Nobody starts with this. A master willing to teach you, a spellbook, and a season of study.",
    src: asset("/img/spellcasting.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JYwCdMoADTuKsvb3eV9eM8kAAAP7p0Q+vq9+vO8NC0pSuyCtccvj6L2UdhT4fBvNeo5qRE/xByUJpHwva8frvU/q08XIp86mgLY/t6fOMv/q+YzDmBD3xCy34dwOcAAA=",
  },
  "holds-map": {
    slug: "holds-map",
    title: "Province of Skyrim",
    caption: "Drawn 4E 182 by Nataly Dravarol, cartographer. Nine holds, nine seats, nine sets of law.",
    src: asset("/img/holds-map.webp"),
    widths: [640],
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoR3ACxx0o3A13YxmCAAye+GteW9RGbg/wPj01wzGcpfmPFgQsPsrKc6wpH72gkf20BBvi0VCvH3/ZPWu3v/Gimf85mo85Y18zJKoRfQ4AA=",
  },
  "night-watch": {
    slug: "night-watch",
    title: "Alone on the pass",
    caption: "Some questions do not have a published answer. You find those out in character.",
    src: asset("/img/night-watch.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwC7ACHM/9x47QdYrgD+6+bHPwP4OUlhB1L9KZH48umrZkY/SAAPAAA=",
  },
  "hold-moot": {
    slug: "hold-moot",
    title: "The hold gathers",
    caption: "The jarl, the steward and every person stood in front of them are players. Nothing here is an NPC keeping a seat warm.",
    src: asset("/img/hold-moot.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JZQCdABag2yqtcpOMAAD+zcS0cGXFUmpprmwFJfcty9iYFVBAQeiyOIHa8s6NY0xmEW9GEzFB36YB6qZg+2EUOoJtPsyERAgwhkIqROGacewU73B35M/0K6AAAA==",
  },
  "the-court": {
    slug: "the-court",
    title: "Court in session",
    caption: "Rank in a hold is granted through the holdstone, and it can be taken back the same way.",
    src: asset("/img/the-court.webp"),
    widths: [640],
    width: 972,
    height: 598,
    blurDataURL:
      "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZQCo9BoeHcwnFiK2ySwAAPzjmsdrhdjGygzSks3UPp00WizwAt58UjWVtfoPfzmD5l2s5IHqd2qt7haLpOS7LLj0JJVZb+x60p1OLe/f5Dv5q7//9DZfHNxZmgr+wAA=",
  },
  "a-jarl": {
    slug: "a-jarl",
    title: "A jarl in his own hall",
    caption: "A jarl is a player, not a scripted NPC. It is the most demanding whitelist on the server, and the seat can be lost as well as won.",
    src: asset("/img/a-jarl.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JbACdMoR4GCmjBABfZoOyWAD+6+zYpX2lxGE5i1eogTQfnw0fvuq5WbHfbF3XSFGXpoJcNizr329X8BRK2fFCQSx+15eE9WnmODZyJAAAAA==",
  },
  "the-legion": {
    slug: "the-legion",
    title: "The Legion, still holding",
    caption: "It is 4E 185, ten years after the Great War. Imperial rule is formally intact and the Thalmor presence is growing.",
    src: asset("/img/the-legion.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JYwCsMoADQcm1WHLvW2FkuwAA/u6oZZScXXeCPiP4WB3wVtnlobLmGnjYhH+zawvKZImnEQ9e96xK4MUDf9yftYRfHz0wNTWVTnzYA1l0THJ99SPwKAAA",
  },
  "under-arms": {
    slug: "under-arms",
    title: "Under arms",
    caption: "An organisation caps at 25 members, and you may belong to one at a time. That is one per player, not one per character.",
    src: asset("/img/under-arms.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwAAW4aB6rNEkudDhtAA/ogW0xYP1Jk4hbYuhXykgE9M7h8PQLgXRYJNtRuXUpzdxiIss9i0uP44mpKe7+eMAAA=",
  },
  "the-muster": {
    slug: "the-muster",
    title: "The muster",
    caption: "A rank in a holdstone carries real mechanical benefits, for example a guard rank granting light armour.",
    src: asset("/img/the-muster.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwC7ACHhcR7GOj4ag3qAAP6jWPpUMSKdTqSddor5CIfuyL5iLOTz5k/NHbeK5fxfGuoluWYLDKSR9zDoThXkhp2Dq6zCj6Q4VyXqRzsf6uVAAAA=",
  },
  "the-harbour": {
    slug: "the-harbour",
    title: "Longships in the shallows",
    caption: "The whole province is playable, so a harbour is somewhere people actually arrive.",
    src: asset("/img/the-harbour.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 759,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAAgAPu1iqk2ppaQiMAgBMB2JZQDG9CHUpy1FVp7eAAD+w4+X3+3t5tFCUQiA/83RMNWFN3lQwAO8rMuxRiwgAAA=",
  },
  "the-arch": {
    slug: "the-arch",
    title: "Old bones in the snow",
    caption: "This site documents the systems. What waits at the bottom of a ruin is not one of them.",
    src: asset("/img/the-arch.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 707,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABQAwCdASoUAAgAPu1iqk4ppaQiMAgBMB2JaQAALEb0lO/jQAD6AUPijUiw/vRWJP1Fvc009fk9AOjMK5S0C06kzu/wOp26ZbAAAA==",
  },
  "the-camp": {
    slug: "the-camp",
    title: "A camp in the woods",
    caption: "Comfort gives fifty percent health regeneration near a camp fire, and it drops the moment you walk away.",
    src: asset("/img/the-camp.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 842,
    blurDataURL:
      "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwBACdASoUAAkAPu1iqk2ppaQiMAgBMB2JaACdMoR3ACP8vc1rQN4x8GZYAAD+7I6TFy7+Yn1IrxnCcFK0VHV+zwfllca/KmS9UEJ11mOXG3xM1ikGE2M/TNAlcaDlwCK6w9/mL4xkmQAA",
  },
  "the-lesson": {
    slug: "the-lesson",
    title: "A lesson in a hall",
    caption: "A master willing to teach you, and a spellbook for the spell. Nobody here teaches themselves.",
    src: asset("/img/the-lesson.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZQAARUR9RXs6gAAA/uNNE1MMI1avFgWNrBhQ+8SgAGDpuxX5uaHMQ+p3Xvgm9K2vI1eF4AA=",
  },
  "the-shrine": {
    slug: "the-shrine",
    title: "By candlelight",
    caption: "A blessing lasts eight hours, and you cannot take a second until the first has worn off.",
    src: asset("/img/the-shrine.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 959,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JQBOmUABwQ4X31dkNYUmDGAAA/uZ5KShHmamHmD0sWiSBOOZWKRz3/na1nUdWtEPqIREvP/pxkiwPP1JmY7t8ZQ9UQAAA",
  },
  "the-kill": {
    slug: "the-kill",
    title: "The kill, and the work after it",
    caption: "Butcher in the field before the skill is high enough and you ruin pelts and ingredients. The client says so in its own tier text.",
    src: asset("/img/the-kill.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwAAUpwkM/1a+aa75iAA/nWGGeClSFm8QJU0lcT+4KFSTb3aiH+ptHG83iRhpgf/KQi3raHl4u+XoMECY7nyIbNaKDU+0YbMNEAYshvc4JdeDHr+T6IVgAA=",
  },
  "the-terrace": {
    slug: "the-terrace",
    title: "Business, done in person",
    caption: "There is no global out-of-character channel. To find something out, you go and ask somebody.",
    src: asset("/img/the-terrace.webp"),
    widths: [640, 1024],
    width: 1732,
    height: 863,
    blurDataURL:
      "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoUAAoAPu1iqU2ppaOiMAgBMB2JQAAJSHjwpy/1iA/y4AD+5b6UgRFBMuxJzG5K4WGQHAIRai4u6YIJbkTS2i0YS+iQQ0h2VAvmU1suiDu7rRfquHEy3KZh0neKkMsYPSxrnLOZ9BwmaqAAAAA=",
  },
  "the-standoff": {
    slug: "the-standoff",
    title: "Something in the mist",
    caption: "Voice is proximity based. If you cannot make out who is talking, neither can your character.",
    src: asset("/img/the-standoff.webp"),
    widths: [640, 1024],
    width: 1650,
    height: 875,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwDCgB6VvLZuXs4JuwSZ8AD+8ReIOOfW3NIipCazMbMHK5jVpKBNelZvF0XAOIRaIoA1DWiAAA==",
  },
  "the-patrol": {
    slug: "the-patrol",
    title: "Into the dark",
    caption: "A cleared dungeon seals, waits on a timer, regenerates and reopens. Keys found inside vanish after thirty minutes.",
    src: asset("/img/the-patrol.webp"),
    widths: [640, 1024],
    width: 1160,
    height: 653,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JaQAAW+nzISMAAAD+9Bv3sQpxfkMUYkOsq3Ic29mn83xyXiem8jZAAAA=",
  },
  "the-long-night": {
    slug: "the-long-night",
    title: "The long night",
    caption: "World time is synced for everyone and runs on the Tamriel year, so night falls on the whole province at once.",
    src: asset("/img/the-long-night.webp"),
    widths: [640],
    width: 900,
    height: 496,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoUAAsAPu1kqU2ppaOiMAgBMB2JZwAAXpNe8PqJd2MBAAD+0mysGXYa6RFe/rUrn0fn/mIUaGylmGAt0OOHKD80qMrn6Z1MfRdOOHLUx57YrrvV9CgAAA==",
  },
  "the-mammoth": {
    slug: "the-mammoth",
    title: "The mammoth, briefly airborne",
    caption: "It is still Skyrim underneath. Some evenings the physics has opinions of its own.",
    src: asset("/img/the-mammoth.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JQBfnAx1B+EUWMWf5AAD+9DJJV4ES96KRlX4DTFHL+ABbL0vkFnnCr3wxZba+fte1CAeSGtpmuoeChKRMtAAA",
  },
  "the-busker": {
    slug: "the-busker",
    title: "Playing to whoever stops",
    caption: "Voice carries by distance, so a song reaches the people standing close enough to hear it and nobody further. Some days that is a full market, and some days it is the rain.",
    src: asset("/img/the-busker.webp"),
    widths: [640, 1024],
    width: 1200,
    height: 830,
    blurDataURL:
      "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoUAA4APu1iqU2ppaOiMAgBMB2JQBOmUABmhBznBQpCDINl4oAA3h8c4J4SNQcEuXHW30/Wv8bjYLZlExebnb2+F8VJh8ACW/EPP1UcQUOL1O3eN05ZSvTIc77JHMPlRzqW7GQwThTM2J+KgixLlL42MDIogfljPEYvkSalBvV0CaUEAAA=",
  },
  "nothing-scheduled": {
    slug: "nothing-scheduled",
    title: "Nothing scheduled",
    caption: "No quest marker put anybody here. Somebody walked out to the end of the boards, sat down, and watched the sky, because that is what their character would do.",
    src: asset("/img/nothing-scheduled.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 940,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoUAAoAPu1kqk4ppaQiMAgBMB2JaQAAV98dxOqF7Pl1QAD+2nmcPxOcHnsfKMOHtZuQa8E3MiuOWasl5/dvk1PEo6rfxwAA",
  },
  "outside-the-hall": {
    slug: "outside-the-hall",
    title: "Sat out under the lights",
    caption: "Conversation happens where people are standing, so a row along a wall outside a hall is a real place to be. There is no global channel to talk in instead.",
    src: asset("/img/outside-the-hall.webp"),
    widths: [640, 1024],
    width: 1700,
    height: 1150,
    blurDataURL:
      "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoUAA4APu1iqU2ppaOiMAgBMB2JYgC06CHhn5myE0aawoG7gAD+6V2PYBVpqZnFwIynSmWU5pm/kqzeKxy/yfaavERBsdxAjP/q37mKOFRBeQJwnj2YzmzGtrbSCEbJOeno3O4+K006qs0VKvNkgmPqcLZwAOnO0VA/Nc+K5h0AAAAA",
  },
  "made-to-be-looked-at": {
    slug: "made-to-be-looked-at",
    title: "Made to be looked at",
    caption: "The paint, the scars and the build are somebody's decisions. You meet people here at speaking distance, so a character is a face long before it is a list of skills.",
    src: asset("/img/made-to-be-looked-at.webp"),
    widths: [640, 1024],
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZQC06C0H2jDIAAD+73ppJKQ937xni7hjqcO243kuJC22NZWD1E4RkkpUJx8F42DiX0eCjtcAAA==",
  },
  "at-the-altar": {
    slug: "at-the-altar",
    title: "At the altar",
    caption: "Candles, an offering and nobody else in the room. Faith here is something a character keeps, not a menu they open.",
    src: asset("/img/at-the-altar.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JQBOmUI7gBVSB+C+6iQBZtXIr5gAA/vD6MbQhi/aX3aNEnmG7jGZo1zi8J3tBUYQJ+fu/25iPwQ0gDP51oqKXYwAZTiGdWj8D8gOL6zrp2wAA",
  },
  "under-the-statue": {
    slug: "under-the-statue",
    title: "Under the statue",
    caption: "The cities are lived in rather than passed through. Somebody put this here, and somebody still sweeps the snow off the step.",
    src: asset("/img/under-the-statue.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZAC7ACLq/IGFEd6lPhyAAP5+MLk9k5HT0N76otv9e376U3FVmAkfUeffKZRwMHcAvKBuh/RrxpR6CTgz+XJo4PrINMRIQdFsw+1rZCZSCAOny6LssAAA",
  },
  "the-empty-throne": {
    slug: "the-empty-throne",
    title: "The empty throne",
    caption: "A seat under the banners of the hold, and the decision about whether to walk up to it. An empty one is filled by moot and by application, never by whoever reaches it first.",
    src: asset("/img/the-empty-throne.webp"),
    widths: [640, 1024],
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JZQC7ACFN5LjYzvhPMarz0sAA/uvjVTG2yI/YBHQS75cbRXhsueqMMTFibgEYl6a59dUSPalYQpub60AhCDCBKTcAAA==",
  },
};

/** Throws rather than rendering a broken image, so a typo fails at build. */
export function plate(slug: string): Plate {
  const found = plates[slug];
  if (found === undefined) throw new Error(`unknown plate "${slug}"`);
  return found;
}
