/**
 * The picture manifest.
 *
 * Generated by `scripts/build-images.mjs` from the originals in `MerethPics/`.
 * Do not edit by hand: change the captions in that script and re-run it, so a
 * picture and its description can never drift apart.
 *
 * Width and height are the real dimensions of the emitted file, which is what
 * lets next/image reserve the space and avoid layout shift. `blurDataURL` is a
 * 20px thumbnail inlined as base64, so a heavy screenshot blurs up rather than
 * popping in.
 */

export interface Plate {
  slug: string;
  title: string;
  caption: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const plates: Record<string, Plate> = {
  "aurora": {
    slug: "aurora",
    title: "Under the aurora",
    caption: "The Sea of Ghosts throws light over the north for most of the year.",
    src: "/img/aurora.webp",
    width: 1280,
    height: 720,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JQBOkFTgtpwxHJ6bwAP13PS3LoL9XfXgCyEVlaspn39zO+UFfE04CQIn6OeAefk+KRISqR4j/SatZZs+aIRegKJy2GcGOuj6RFooH8b4OTgAAAAA=",
  },
  "old-ways": {
    slug: "old-ways",
    title: "The old ways",
    caption: "Clevercraft is the ancestral tradition of Skyrim's people. Where you find magic and Nords together, expect a fire and a shaman.",
    src: "/img/old-ways.webp",
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwAAW+wPMGJEEAAA/vQig17sdtxM00MLM09qJV9IoOd+wzwWWAAA",
  },
  "mead-hall": {
    slug: "mead-hall",
    title: "A hall in the evening",
    caption: "Most of what happens on Mereth happens at a table, over a longfire.",
    src: "/img/mead-hall.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCdACHfLUEYKGo4j+cntKwAAP7lbIGx6N6e+6tKEj3h1WKRt6UtKHmrsa+bZM4rOV5l9+mJYL2XqVzLcu1gAAA=",
  },
  "jarls-hall": {
    slug: "jarls-hall",
    title: "The jarl's hall",
    caption: "Court is held where the hold eats. Rank here is granted, and it can be taken back.",
    src: "/img/jarls-hall.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JQBOgBDfa/g+FQ8Je5gAA/r2mv4ZstVGBhZwQ1+fx8I9aawJ6kwsRUAZPPU0+vpSG5ssJOtn4iGE58BLO/q7WzVe1BLVy/MAAAA==",
  },
  "hold-guard": {
    slug: "hold-guard",
    title: "The hold guard",
    caption: "Guards are players. So is whoever they are waiting for.",
    src: "/img/hold-guard.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JQBadBH8zI0IvHiGmYAD+wA2I7bfsaqXNBYbR+Q4y46+wrJfD48I75WON1gs0LcgIt1oRfSYDhGgEbcdIpw5fjbH9JQmlnjK742TL1GFYwFEObvHvF4TnnWMsAA==",
  },
  "longfire": {
    slug: "longfire",
    title: "Around the longfire",
    caption: "Sat down, armed, and in no hurry. An ordinary evening.",
    src: "/img/longfire.webp",
    width: 1800,
    height: 753,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUAAgAPu1iqU2ppaQiMAgBMB2JYgCdMoADa3/pfrCiA77mBugAAP68ZIYIsP61PhJpBvCTRjBITjXmNB/gAsOQqHWgdgHX5feD76VfwHxmv3NNCeioChz4AAA=",
  },
  "winter-port": {
    slug: "winter-port",
    title: "A port in winter",
    caption: "Nine holds, each with its own law, its own court and its own trade.",
    src: "/img/winter-port.webp",
    width: 1800,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7ABgNRYCaEd+ZwAD+hvuDv/wKCZQphVKbo8JLYGtRe6QpOAcy5ESpypXQda/DbpYgsRTMEGa+Kvj8eWSXjRJpLdXtwAA=",
  },
  "palisade": {
    slug: "palisade",
    title: "Beyond the palisade",
    caption: "The province is the whole map, and the weather in it is not on your side.",
    src: "/img/palisade.webp",
    width: 1800,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZwCw7BYEQPaS9OGAoAD+1Lc9ip9y9iRrhSjUz9S3aUmcApVjnAoay3ezPuqa5utCZaIZzpCAp7JzHroUIuT3NSxfZzLGzuGbYjaz1q8wGQed8HPCAA==",
  },
  "arriving": {
    slug: "arriving",
    title: "Arriving",
    caption: "Carry weight is a real constraint. The answer to it is crafted, not bought.",
    src: "/img/arriving.webp",
    width: 981,
    height: 555,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JZQC/OCGInJvlMt8nZAAA/qFsP6bf5RtVnzSqY1I40vqcFNyjOFPXBhbHJxmT/coMVjTNsjyes+1TO4+z+D+oAAA=",
  },
  "mammoths": {
    slug: "mammoths",
    title: "The hunt",
    caption: "Hunting, herbalism, mining, fishing. Eight gathering trades, each with its own nodes.",
    src: "/img/mammoths.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JZwBUgo/4DbvT2B8+J0XnVAAA/rro4dDFscShH0EzGcBft6ihyIsz8h7uZfVrM3U33c9Qru/tZth6ZE1JZbbwfbDiAAAA",
  },
  "skill-menu": {
    slug: "skill-menu",
    title: "The skill plan",
    caption: "Press K. Eighteen memory points across 51 skills, and the tier you buy is the ceiling that skill can ever reach.",
    src: "/img/skill-menu.webp",
    width: 1800,
    height: 956,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAwCdASoUAAsAPu1iqk2ppaQiMAgBMB2JZwDLLCKUYf63H+nYfSAAAP7sZrBShPAaOVahu9uDvtX3LggoZAke56NLo6tHfnAAAA==",
  },
  "spellcasting": {
    slug: "spellcasting",
    title: "A spell, finally",
    caption: "Nobody starts with this. A master willing to teach you, a spellbook, and a season of study.",
    src: "/img/spellcasting.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoUAAsAPu1iqU2ppaQiMAgBMB2JYwCdMoADTuKsvb3eV9eM8kAAAP7p0Q+vq9+vO8NC0pSuyCtccvj6L2UdhT4fBvNeo5qRE/xByUJpHwva8frvU/q08XIp86mgLY/t6fOMv/q+YzDmBD3xCy34dwOcAAA=",
  },
  "holds-map": {
    slug: "holds-map",
    title: "Province of Skyrim",
    caption: "Drawn 4E 182 by Nataly Dravarol, cartographer. Nine holds, nine seats, nine sets of law.",
    src: "/img/holds-map.webp",
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoR3ACxx0o3A13YxmCAAye+GteW9RGbg/wPj01wzGcpfmPFgQsPsrKc6wpH72gkf20BBvi0VCvH3/ZPWu3v/Gimf85mo85Y18zJKoRfQ4AA=",
  },
  "night-watch": {
    slug: "night-watch",
    title: "Alone on the pass",
    caption: "Some questions do not have a published answer. You find those out in character.",
    src: "/img/night-watch.webp",
    width: 1800,
    height: 1013,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwC7ACHM/9x47QdYrgD+6+bHPwP4OUlhB1L9KZH48umrZkY/SAAPAAA=",
  },
};

/** Throws rather than rendering a broken image, so a typo fails at build. */
export function plate(slug: string): Plate {
  const found = plates[slug];
  if (found === undefined) throw new Error(`unknown plate "${slug}"`);
  return found;
}
