import { chronicleRegister } from "@/lib/world/calendar";
import { loreShelves as publishedShelves, type LoreDocument, type LoreShelf } from "@/lib/world/lore";

/**
 * The library, which is now two sources and one shelf list.
 *
 * `lore.ts` is generated by `scripts/build-lore.mjs` from the documents in
 * Mereth's own website repository and must not be edited by hand. The lore
 * office in the staff console is the second source: documents written there and
 * published land in `chronicle.json`, and they belong on the same shelves as
 * the rest rather than in a second library that reads as less official.
 *
 * So the merge happens here, and the generated file stays generated.
 *
 * ## Why a document needs a deploy and an event does not
 *
 * The calendar corrects itself in the browser, so an event published in the
 * office appears for readers within a couple of minutes. A document cannot work
 * that way, and the reason is structural rather than an oversight: every
 * document has its own URL, `/lore/<slug>`, and this site is a static export.
 * A file host can only serve a page that exists as a file, and that file is
 * written at build time. A document published in the office therefore appears
 * **at the next deploy**, not immediately.
 *
 * That is stated in the office's own UI, next to the publish button, so nobody
 * publishes and then wonders for an afternoon why the page is not there.
 */

/** A shelf id the office can write to that the generated file has never seen. */
const SHELF_TITLES: Record<string, { title: string; blurb: string }> = {
  orders: { title: "The orders", blurb: "The factions, in their own words." },
  province: { title: "The province", blurb: "The land, its holds and who holds them." },
  scholarship: { title: "Scholarship", blurb: "Study, magic and the people who write about them." },
  law: { title: "Law and rule", blurb: "What the province asks of the people in it." },
};

function officeDocuments(): Map<string, LoreDocument[]> {
  const byShelf = new Map<string, LoreDocument[]>();

  for (const entry of chronicleRegister.lore) {
    /*
     * A document with no slug or no paragraphs is skipped rather than rendered
     * empty. The office cannot produce one, but this file also reads a JSON
     * bundle that a sync wrote, and the sync's input is a network answer.
     */
    if (entry.slug === undefined || entry.slug === "" || entry.paragraphs.length === 0) continue;

    const shelf = entry.shelf === "" ? "province" : entry.shelf;
    const documents = byShelf.get(shelf) ?? [];
    documents.push({
      slug: entry.slug,
      title: entry.title,
      note: entry.note,
      paragraphs: entry.paragraphs,
    });
    byShelf.set(shelf, documents);
  }

  return byShelf;
}

/**
 * Every shelf, with the office's documents folded into the ones they belong to.
 *
 * Office documents go last within a shelf. The published documents were written
 * first and are what a returning reader is looking for, and a new one arriving
 * should not reorder the shelf under them.
 */
export const libraryShelves: LoreShelf[] = (() => {
  const office = officeDocuments();
  const merged: LoreShelf[] = publishedShelves.map((shelf) => {
    const extra = office.get(shelf.id) ?? [];
    office.delete(shelf.id);
    return extra.length === 0 ? shelf : { ...shelf, documents: [...shelf.documents, ...extra] };
  });

  // A shelf the office invented that the generated file has no entry for. It
  // still gets rendered: dropping somebody's published document because its
  // shelf is unfamiliar would be losing content to a naming mismatch.
  for (const [id, documents] of office) {
    const known = SHELF_TITLES[id];
    merged.push({
      id,
      title: known?.title ?? id.replace(/^\w/, (c) => c.toUpperCase()),
      blurb: known?.blurb ?? "Written in the lore office.",
      documents,
    });
  }

  return merged;
})();

export const libraryDocuments: LoreDocument[] = libraryShelves.flatMap((shelf) => shelf.documents);

/** Throws at build rather than rendering an empty page. */
export function libraryDocument(slug: string): LoreDocument {
  const found = libraryDocuments.find((document) => document.slug === slug);
  if (found === undefined) throw new Error(`unknown lore document: ${slug}`);
  return found;
}
