/**
 * Mereth's published lore, as written.
 *
 * Generated by `scripts/build-lore.mjs` from the lore folder of Mereth's own
 * website repository. Do not edit by hand: change the source documents and
 * re-run it, so this site can never drift from the text the team published.
 *
 * The documents are reproduced in full. They are somebody's writing, and the
 * point of putting them here is that a player can read them, not that the site
 * can summarise them.
 */

export interface LoreDocument {
  slug: string;
  title: string;
  /** One line on why a reader would open this one. */
  note: string;
  /** Where a reader most likely wants to go after finishing it. */
  related?: { href: string; label: string };
  paragraphs: string[];
}

export interface LoreShelf {
  id: string;
  title: string;
  blurb: string;
  documents: LoreDocument[];
}

export const loreShelves: LoreShelf[] = [
  {
    "id": "orders",
    "title": "The orders",
    "blurb": "The three lore factions, in their own words and in the words of people who left them.",
    "documents": [
      {
        "slug": "companions",
        "title": "The Companions",
        "note": "The hall at Whiterun, and the mantle nobody has claimed for forty years.",
        "related": {
          "href": "/factions",
          "label": "What the Companions are in play"
        },
        "paragraphs": [
          "The fields of Whiterun, the heart of the Fatherland, have for millennia been home to the storied Hall of Jorrvaskr and the valiant Nord Companions. From the days of Ysgramor, the Companions have ever held the honor of all Nords and the growing realm of Skyrim in their words and deeds, unyielding in valor and strength; however, darkness has fallen upon the Meadhall of the Hoary King, and mirth rings out in the ancient ship's bones no more.",
          "Ere some 60 years, shield brother and shield sister took up arms against one another in vile disagreement over one question: Who shall uphold the honor of the Companions and take up the mantle of Harbinger? It was decided that to claim Jorrvaskr was to prove the honor of one's claim, and from the division between Jorm Orc-born and Lok Merkiller came the 20 years of infighting known now as the Blood-Score.",
          "It has been twice as long now since either would-be Harbinger died a gloriously bloody death, and yet the mighty hall remains unconquered. Some say it is fear of more bloodshed that prevents these so-called Companions from stepping forth, others believe that the ancient warriors are no more. The legacy of the Companions is not gone, however, and if a band of brothers and sisters had only the courage to stand once again for the honor of Skyrim, of ancient Nord culture, and of Ysgramor, then it need not stay in the history books."
        ]
      },
      {
        "slug": "harbinger-reflections",
        "title": "The Harbinger’s Reflections on the Decline of the Guild",
        "note": "A Harbinger writing on how the Companions declined.",
        "related": {
          "href": "/factions",
          "label": "What the Companions are in play"
        },
        "paragraphs": [
          "To Jorm, trusted shield brother",
          "Brother, I see clearly the path we are walking. Many speak of strength as if it were an absolute virtue. Yet the history of the North is filled with peoples who were strong… and nonetheless vanished. The Snow Elves did not fall only beneath the axes of our ancestors. They fell because something within them broke long before their walls did. When a people lose their bond with what they hold sacred, a descent begins that no sword can halt. It is not always a divine punishment. Sometimes it is a slow fading, like snow beneath a sun that cannot be seen. I have studied the tales of their gods, of the temples that shone in the mountains, and of prayers said to be able to still the winter itself. If any of this is true, then their ruin was not merely material. It was spiritual. A gradual estrangement from their own origin. And here I find a warning for us. We do not need curses or dark magic to fall into oblivion. It is enough to forget why we fight. Enough to let glory replace meaning. Enough to stop listening to the silence between one battle and the next. The Snow Elves became unrecognizable not because they were transformed… but because they ceased to recognize themselves. This is the true fall. Not defeat. Not the loss of land. But the moment when memory can no longer sustain identity. If their gods abandoned them, perhaps it was not out of cruelty. Perhaps it happened because there was no one left able to hear them. We, who call ourselves Companions, must guard against this more than against any enemy. For walls can be rebuilt. Weapons reforged. Wounds healed. But when a people forget themselves, no smith can save them. And then the snow, which once held their songs, becomes only silence.",
          "Brother Dainn"
        ]
      },
      {
        "slug": "greymane-skyforge-letter",
        "title": "Letter from Yjorn Gray-Mane, Custodian of the Skyforge",
        "note": "The custodian of the Skyforge, on why his hammer is still.",
        "related": {
          "href": "/crafting",
          "label": "Smithing, and what a bench can make"
        },
        "paragraphs": [
          "To the Companions of Jorrvaskr, or whoever finds this letter",
          "I write these words in the shadow of silence, far from prying eyes and listening ears, for what I must say weighs upon my heart like an anvil upon the chest.",
          "For centuries before me and before the fathers of our fathers, my lineage has stood as custodian of the Skyforge. The Gray-Manes have never been mere smiths: we have been guardians of knowledge as ancient as the stones of Whiterun itself. The secret of Skyforge steel is no simple craft, but a sacred inheritance, entrusted to our family so that it might serve a worthy cause, the glory and honor of the Companions.",
          "Yet now I see division where once there was brotherhood. This internecine strife, born of pride and fed by suspicion, will bring neither strength nor honor, but only ruin. Your blades, once symbols of protection and valor, risk becoming instruments of discord and shame.",
          "I cannot, in good conscience, feed with my hammer a conflict that stains the name which once made enemies tremble and brought comfort to the innocent. Until the good name of the Companions of Jorrvaskr is restored, until unity once again becomes your banner, my family shall forge no more weapons for you.",
          "The craft of forging Skyforge steel shall remain guarded in silence, as it has been in the darkest of times. It shall not be passed on, nor shared, nor used to fuel this fratricidal folly.",
          "Remember who you are. Remember what you stand for. You are not merely warriors: you are brothers bound by honor, oath, and the memory of those who came before you.",
          "When you become worthy of your name once more, when your brotherhood stands stronger than your divisions, then, and only then, shall the fires of the Skyforge sing for you again.",
          "Until that day, my hammer shall remain still.",
          "Yjorn Gray-Mane",
          "Custodian of the Skyforge"
        ]
      },
      {
        "slug": "shield-brother-letters",
        "title": "Letters of a Shield Brother in Times of Turmoil",
        "note": "Letters between shield brothers during the turmoil.",
        "related": {
          "href": "/factions",
          "label": "The three orders, and their caps"
        },
        "paragraphs": [
          "Brother, tonight I drank with the others in the long hall. The laughter was loud, the cups full, the stories greater than usual. And yet, beneath that noise, I felt the pulse of something older. Not the drum of war. Not the song of heroes. But the call of the hunt. Primal instincts passed down by our ancestors. When I look into the fire, I do not see a gift. I see a promise made too quickly.",
          "They teach us that to die with a sword in hand is glory. That the halls of heroes welcome the valiant. That the memory of a righteous life is stronger than death. But what welcomes one who has run as an animal? If my soul has learned to snarl more than to sing, where will it be taken when my heart stops? Among the ancestors… or among the shadows that hunt forever? They tell me it does not matter. That strength justifies the price. I am beginning to believe the price is the most important part.",
          "I have studied the stories of the ancients. The heroes who crossed the frozen sea needed not to be feared. They needed no praise to be great. They had will. Now we lack power. and less will than we admit. Perhaps this way of living is not our curse. Perhaps it is our excuse.",
          "Tonight I refused to run with the others. I said the wounds of battle kept me from the fight. It was a lie. The truth is I fear what I am becoming when I cease to remember my own name in the midst of the bloodbath. These battle brothers do not want glory. They do not want brotherhood. They do not want remembrance. It wants only the moment. And if a warrior’s life is made of moments without memory, then we are no longer heirs of heroes. We are only storms of flesh.",
          "If you read these words, I will have already made my choice. I do not renounce the strength that was given to me. But I cannot accept that it will define what I am after death. One day they will still sing of us. They will say we were invincible. That we were blessed. I hope they will also say that one of us had the courage to fear his own victory. Because not all battles are fought with fangs. Some are fought by remembering we are men.",
          "Hroldar"
        ]
      },
      {
        "slug": "college-winterhold",
        "title": "The College of Winterhold",
        "note": "The College, its semesters, and what it asks of applicants.",
        "related": {
          "href": "/magic",
          "label": "How a spell is actually learned"
        },
        "paragraphs": [
          "Skyrim is a land renowned for its frozen peaks and harsh storms, but one cannot truly appreciate what it means to be of this land until they have weathered the jagged shores battered by the Sea of Ghosts. Glaciers drift in the frozen fog as massive ice sheets pretend at being land - until they crack upon and plunge the unwary wanderer into a fathomless frozen sea. It is upon these shores that myth and memory are preserved, almost drawing out from the Ghosts what memories they retain of ancient Atmora, and are safeguarded at the College of Winterhold.",
          "The College traces its history to the Cleverfolk, the shamans and spellsingers of the ancient Nords, and the worship of the Nordic Owl Totem. Though now mistrusted by the denizens of Skyrim, a great many Nords still hone their Craft under the watchful gaze of Jhunal, and are more than willing to impart their history and knowledge upon the stranger and foreigner alike. Many former Mage's Guild neophytes have been drawn to Winterhold out of curiosity, as the philosophies of spellwork found within - the perception of magicka as a force of nature - are vastly different from the more manufactured and Aetheric teachings of Vanus Galerion.",
          "However, the true depth of this ancient land's mystical history cannot be contained within the walls of a reliquary; the history lives on in the wilds of Skyrim, continued in its living praxis by hedgewitches and Ternion monks and everything in between. Nords of today still live in the long shadows of their ancestors, and while few may wish to give it the respect it deserves, the Clever Craft dies in name alone, for its lessons are evergreen."
        ]
      },
      {
        "slug": "thieves-guild",
        "title": "The Thieves' Guild",
        "note": "What the Guild is in Skyrim, told plainly.",
        "related": {
          "href": "/rules",
          "label": "The rules on robbery and theft"
        },
        "paragraphs": [
          "To outlanders, Skyrim is a land of harsh storms, enduring traditions, strong warriors, and honorable - if brutal - cultural inheritance. The Nords are equally hardy, sons and daughters of storm and sky, and none would imagine first among Nords the ways of stealth or subterfuge; regardless, where there is light, there must be shadow. Where there is law, there must be crime, and not all criminals of the land are brazen challengers and highwaymen. Like in all places across Tamriel, the quick-witted and sly meet with the unscrupulous and deft to create a mutually beneficial system of advantage - in short, a Thieves' Guild.",
          "In stark contrast to this grand Atmoran legacy, hidden in the shadows of betrayal and coin, the Thieves' Guild thrives buried under ice. Some say that the Guild exists solely as an interloper of Imperial culture, that true Sons and Daughters of Kyne would never engage in such dishonorable criminality, but others argue that this Guild shares only its name with the provincial counterparts: clans, both storied and new, trade alliances, services, agents, and gold, all sharing the same mask of the most notorious of collectives.",
          "In the wake of the Great War, the clans and collectives of Skyrim's Guild have enjoyed a berth of opportunity and profit. In harmony with its nature as a dark mirror to society, the Thieves' Guild thrives with tragedy and must prepare to face the hardships of peace - with the White-Gold Concordat growing ever further behind, the threat of stability might mean a lack of desperation. Furthermore, the machinations of individual clans are unending, and none can ever feel certain of the loyalty of thieves."
        ]
      }
    ]
  },
  {
    "id": "faith",
    "title": "Magic and faith",
    "blurb": "Where the province's magic comes from, and who is permitted to teach it.",
    "documents": [
      {
        "slug": "atmoran-clevercraft",
        "title": "Atmoran Clevercraft",
        "note": "Clevercraft, and what Shalidor left behind.",
        "related": {
          "href": "/magic",
          "label": "Every spell, with its tier"
        },
        "paragraphs": [
          "The Secrets of Shalidor’s Legacy",
          "By Laah’dan of Atmora",
          "Hark, Sons of Wind and Winter! Pay heed, Daughters of Root and River! Too long have the long-eared lies of the Fox’s foemen filled our minds with mire and muck! I arrive from ancient Atmora, hewn from the homeland by the hardy hands of our oldest faith-ways, to rebirth rites and rituals, sacred sorceries and the totemic truth!",
          "If one thing should the brood of the Hawk and followers of the Owl unlearn, it is the angular magic of Mer. The elf turns its back upon the Maker, and to do so is to face the stars. To study starlore is to know gods, but where Man kneels, Mer grasp for power, do not learn this, children of Men! Aetherius is a realm of gods, which we as their children may wield, but know that the Earthbones are our true well of power. The Maker, that clever Fox, put in all matter the spark of Magicka, handcrafted for our hands to craft. It is He who sends us starlight to fuel fire, He who ensouled beasts to strengthen our swords, and yes, He who even imbued bone with a bulwark greater than the frailties and failings of flesh.",
          "These are the hidden truths of Atmora, spake soul-to-soul from the hardening homeland. Mankind’s making ought observe the truth, clever craft unveiled. The Maker did not err in His worldcraft, thus all tools we find upon the Maker’s world are for Mankind to wield. The elf longs to escape the everwise emanation of our Maker, so he will curse the conjurer who calls upon those corpses whose children did not honor them, but I ask of you, if the wight is unwarded from wayward spellweave, then why should the sorcerer stay his spellcraft? The Maker sings all slain spirits into the sleeve of dreaming, but sinew has strength in it yet, and to scorn such skill is to rebuke the right of resource. A spriggan serves the forest in life, but her wood warps to the will of craftsmen in death.",
          "Heed not the hearsay of the Mage’s Guild! Made of the mold of Mer-like magic, all they hold dear, from their rituals to their robes, are bereft of the base acceptance that the Mundus and our Maker must imbue spellwork from the onset. You may ask yourself what recourse comes of these revelations, and I point to the studies and scholarship of Shalidor Spellbreaker, the true Archmagus of Mundus. A mage unmatched, an archon of Atmoran acuity, Spellbreaker was a concealed courier of clevercraft tradition, a Clever Man unlike any since. Many misunderstand his relation to the revenants of the draugr, thinking that Shalidor sought to nullify necromantic knowledge, but how can one maintain mastery over the labyrinths of ancient Atmoran burial barrows and not wield the weave of wightedness?",
          "A Man, son of Sky, so rooted in the realm of Shor, son of Shor, that he became known to all as Archmage unrivaled. In Bromjunaar, we uncover the truth."
        ]
      },
      {
        "slug": "bron-laahdan-treatise",
        "title": "On The Learnings of Bron Laah’dan",
        "note": "A treatise dictated by a master, on the learnings of Bron Laah'dan.",
        "related": {
          "href": "/magic",
          "label": "How a spell is actually learned"
        },
        "paragraphs": [
          "A Scholarly Treatise",
          "Dictated by Master of Alteration Halgaar Frost-Fingers",
          "Penned by Apprentice Julienne",
          "In the 17th year of the 4th Age, the most controversial of mages arrived at the shores of Winterhold. He called himself “Laah’dan of Atmora”, a name that garnered much scrutiny from the historians of the College, given that the last man known to hail from Atmora was Talos Stormcrown in the 2nd Age. Nevertheless, he proved himself a strong and capable mage in the fashion of our own history, he venerated the Owl Totem that we call Juhnal in his spellwork, and he quickly rose from Initiate to Apprentice to Journeyman.",
          "It was Laah'dan who ignited our modern interest in Shalidor's ancient Labyrinthian, and no Master of the College would deny the benefits his influence has had on our continued study and research of ancient magical traditions, but his legacy does not end with trinkets recovered from ruins. Indeed, many have pointed to this so-called Atmoran in discussion of the resurgent necromantic practices in Winterhold. Most damning of all, however, is the clear inspiration taken by the progenitors of the Dragon Totem Schism of 4e82, who frequently cited Laah'dan under the names Bron the Faith Breaker, Bruhn’daan of the True Voice, and at times simply calling him by “Atmora” itself.",
          "How shall we judge the legacy of such a man? Some of his theories revolutionized our understanding of history and magic, while others bordered on the heretical. His practices were just as variable, bridging the ends of a moral spectrum in ways dizzying to comprehend. In the following pages, I intend to detangle the scholar from the charlatan and bring to heel the wild fantasies of the mage I believe we ought to know as Hagar Helmsson, a Skaal shaman from Solstheim."
        ]
      },
      {
        "slug": "vigilant-rule-4e35",
        "title": "The Vigilant Rule of 4E 35",
        "note": "The rule written for the newly founded Knights Vigilant.",
        "related": {
          "href": "/factions",
          "label": "Organisations, and what they may hold"
        },
        "paragraphs": [
          "Penned for the Newly Founded Knights Vigilant, or, The Vigilants of Stendarr, by First Keeper Maurice of Glenpoint",
          "It has been 30 years since we first took our vows; then, we were known as Crusaders, sworn guards of Stendarr’s temple. We knew then, as we say now with vigor, that our oaths would draw us out beyond the narrow scope of defending that holy building. We knew that Stendarr’s Mercy would not cease at the doors of a temple, but must be brought to a world beset by foul aberrations of Oblivion. Brothers and sisters, it is my sincerest hope that this codex serves our order well into its years, and that our Vigil will stand strong for many, many years to come.",
          "“Listen closely, initiate. To wear the amulet of the Steadfast is to live by a code of steel and spirit. If you falter, you do not just fail yourself, you leave an opening for the Daedra to slip through.”",
          "In the unholiest of nights, the Commandments of the Vigil have been a steadfast spiritual rigor and conferment of strength to persevere. All brothers and sisters must bear them in mind, body, and soul, until their last breath.",
          "You shall have no commerce with Daedra. You will not speak their names in reverence, you will not strike bargains for their 'gifts,' and you will never wield their cursed artifacts. To touch a Daedric Prince’s relic is to stain your soul; such items must be seized and brought to the Vigil for containment or destruction.",
          "Stendarr is the God of Charity. You are required to offer healing to any mortal who is diseased or injured, provided they do not serve the dark. We take no gold for these blessings; our payment is the restoration of the innocent.",
          "We do not use the blades of common sellswords. You shall train in the use of the mace and the warhammer. It is the traditional weapon of our order, designed to crush the bone of the undead and the armor of the cultist alike.",
          "A Vigilant’s best defense is their faith. You must master the Schools of Restoration and Alteration. Your magic is not for vanity, but to create wards against Daedric fire and to harden your skin like oak when the beast strikes.",
          "Do not be swayed by 'civilised' monsters. A vampire in a fine doublet is still a parasite. A werewolf who claims to control the beast is still a ticking clock of carnage. The Vigil has no mercy to spare for the Abominations, only the peace of the grave.",
          "You serve the Order. Whether stationed at a Hall or patrolling the wilderness, you go where the corruption is thickest. You report all sightings of Daedric influence to the Keeper immediately.",
          "To follow the Light is one thing - to stay alive while doing so is another. The Vigil is not merely a sect of monks set upon a mission, we are a Knightly Order, and must engage with the acumen that befits our station.",
          "No one Vigilant will ever be enough to both defend the innocent and vanquish darkness. All Knights will travel in pairs, a number small enough to move quickly but not leaving a single Knight without an earthly ally. The senior Knight will always see first to the defense of the defenseless, and only when Stendarr’s Mercy is enacted will he turn to aid his brother in the banishing of abhorrence.",
          "All Vigilants are always prepared to pay the ultimate price in the service of our Lord Stendarr. There are select instances, however, in which the greater good calls not for the life of a Vigilant, but his continued strength:",
          "In such case that the Vigilant’s death will leave innocents defenseless, his duty must instead be to escort as many innocents to safety as possible.",
          "At such time that the Vigilant’s death will not meaningfully halt the onslaught of aberrations, will not afford ample time to his allies elsewhere, and will not provide defense for the defenseless, it is a greater cause for the Vigilant to survive such that his strength may be added to that of his brothers in battles yet to come.",
          "The Vigilant does not retreat for fear of casualty or safety; each brother and each sister knows the value of our cause, and will not so easily be cowed. The sole Contingency of Retreat, however, is that no Knight Vigilant shall pursue glory over our great calling. When the strategic choice is to inform the Vigil and return with more brothers, and it does not endanger the common people to do so, no Vigilant shall engage the enemy underprepared. We are trained to lay down our lives, but Stendarr does not honor those who throw their lives to the wolves like scrap."
        ]
      }
    ]
  },
  {
    "id": "power",
    "title": "Law and power",
    "blurb": "Who holds the province, and who is working against them.",
    "documents": [
      {
        "slug": "imperial-legion-4e185",
        "title": "The Imperial Legion in Skyrim, 4E 185",
        "note": "An account of Imperial order and dominance, dated to the present year.",
        "related": {
          "href": "/holds",
          "label": "The nine seats, and who sits them"
        },
        "paragraphs": [
          "An Account of Order, Duty, and Dominion in a Divided Land",
          "In these years after the Great War, amidst the cold winds and brittle loyalties of Skyrim, the Imperial Legion stands as both shield and symbol of the Empire’s enduring authority. Our presence in the province today is not purely that of a military force, but as a stabilizing power striving to preserve unity in a land threatened by the Aldmeri Dominion and religious grievances.",
          "Structurally, the Legion shall always maintain its traditional hierarchy. Legionnaires forming the backbone, supported by auxiliary troops and specialized officers. These soldiers are stationed across the Holds, most notably in Solitude, the seat of Imperial power in Skyrim. Forts scattered throughout the holds serve both as defensive positions.",
          "Your purpose in Skyrim during this time is two sided. First, you seek to suppress any insurrections to preserve not only Imperial authority but also the fragile peace established by the White-Gold Concordat. Second, you are to uphold the law and order in a province walking on the edge of chaos. Banditry, unrest, and uneasy loyalties plague the land, and we serve as the last bastion of structured governance in many regions.",
          "Although, your presence is not without controversy. To many Nords, it represents foreign control and the suppression of their traditions, particularly the banning of Talos worship. To others, it is a necessary force, preventing Skyrim from descending into complete anarchy or falling prey to external threats, such as the ever-watchful Aldmeri Dominion.",
          "Despite these tensions, soldiers of the Imperial Legion remain bound by a singular creed: duty to the Empire above all. We are not merely conquerors, but guardians of an ideal that a unified Empire, though imperfect, offers greater stability than chaotic division.",
          "Therefore, in 4E 185, the Imperial Legion in Skyrim stands at a tipping point. You are both occupier and protector, resented and relied upon, fighting a battle for the very identity of the province. Whether history will remember our Legion as a tyrant or savior remains uncertain, but our mark upon Skyrim is definite, and your duty remains to the Empire."
        ]
      },
      {
        "slug": "penitus-skyrim-report",
        "title": "Criminal Underworld in Skyrim",
        "note": "A report on criminal enterprises, compiled for the Emperor.",
        "related": {
          "href": "/rules",
          "label": "What the rules allow a criminal to do"
        },
        "paragraphs": [
          "Report compiled for the Emperor",
          "Director Mattius Locundus, Headmaster of the Imperial Order of the Penitus Occulatus, Personal secretary to the Emperor",
          "I have the honour to write this report for your eyes only.",
          "This report is the compilation of a year of effort of your majesty’s most loyal agents.",
          "The status of the criminal underworld in Skyrim is as follows.",
          "It has been known to us so far that various native criminal organizations have long since been subsumed into the Thieves Guild, which gives the local guild a unique character compared to its counterparts in other provinces. However, our sources have yet to fully identify the specific composite organizations, one thread of which we followed suggests a possible influence from a native nocturnal cult, though the nature of influence on the guild, or the size of this cult, cannot be gauged, it may be possible that this is merely a subsect within the guild, rather than a driving force.",
          "So far, given the recent devastation in Cyrodiil and the mass amount of retiring soldiers, there has been an uptick in demand for property within Skyrim. This has led, along with the recovery efforts in Cyrodiil, to a notable increase in the prices of goods and property within Skyrim, which has contributed to an increase in the number of members within the guild. Our source within the guild suggests a notable tension between old native members and newer members from Cyrodiil. The present conflict may be tied to a possible cult within the guild, though our source believes it stems from conflicting interests and methods.",
          "Much like Cyrodiil and High Rock, Skyrim is experiencing an uptick in banditry, though no cohesive bandit organization exists for this to be much of note, or worry, for the imperial administration; currently, the Guild holds the sole monopoly on organized crime within the province, though possible nationalist groups, both Reachfolk, and Nord groups, may move into the criminal underworld.",
          "Given the possibility of nationalist groups going underground, it is the recommendation of this report that the Penitus Occulatus further infiltrate the Thieves guild, and attempt to drive policy in such a way as to maintain a sole monopoly. If local nationalist groups form their own enterprises, this would pose a notable risk to imperial investments.",
          "I have the honor to be, Sir, your most Humble and Obedient Servant,",
          "Lurius Floria",
          "Director of Imperial Intelligence in Skyrim"
        ]
      }
    ]
  }
];

export const loreDocuments: LoreDocument[] = loreShelves.flatMap((shelf) => shelf.documents);

/** Throws at build rather than rendering an empty page. */
export function loreDocument(slug: string): LoreDocument {
  const found = loreDocuments.find((document) => document.slug === slug);
  if (found === undefined) throw new Error(`unknown lore document: ${slug}`);
  return found;
}
